-- Attempt 7: gc and coroutines (should be harmless)
print("collectgarbage:", type(collectgarbage))
print("gc count:", collectgarbage("count"))
collectgarbage("collect")
print("gc collect: ok")
local co = coroutine.create(function() coroutine.yield(42) end)
local ok, v = coroutine.resume(co)
print("coroutine:", ok and ("yielded "..tostring(v)) or "failed")
-- coroutine with infinite loop (separate test for hang)
print("coroutine basic: harmless")
